class SpecificationModel {
  int? id, brandId;
  String? title,
      description,
      technology,
      announced,
      status,
      dimensions,
      weight,
      build,
      sim,
      typeDisplay,
      size,
      resolution,
      protection,
      os,
      chipset,
      cpu,
      gpu,
      cardSlot,
      internal,
      triple,
      features,
      video,
      loudSpeakerSound,
      jack,
      wlan,
      bluetooth,
      gps,
      nfc,
      radio,
      usb,
      sensors,
      typeBattery,
      charging,
      colors,
      models,
      sar,
      sarEU,
      price,
      camera,
      loudSpeakerTest,
      quad,
      dual,
      single,
      scVideo,
      scFeatures,
      scSingle,
      scDual,
      displayTest,
      performanceTest,
      batteryLife;
  List<String>? images;

  SpecificationModel(
      {this.id,
      this.brandId,
      this.title,
      this.description,
      this.technology,
      this.announced,
      this.status,
      this.dimensions,
      this.weight,
      this.build,
      this.sim,
      this.typeDisplay,
      this.size,
      this.resolution,
      this.protection,
      this.os,
      this.chipset,
      this.cpu,
      this.gpu,
      this.dual,
      this.cardSlot,
      this.internal,
      this.triple,
      this.features,
      this.video,
      this.loudSpeakerSound,
      this.jack,
      this.wlan,
      this.bluetooth,
      this.gps,
      this.nfc,
      this.radio,
      this.usb,
      this.sensors,
      this.typeBattery,
      this.charging,
      this.colors,
      this.models,
      this.sar,
      this.sarEU,
      this.price,
      this.camera,
      this.loudSpeakerTest,
      this.batteryLife,
      this.quad,
      this.single,
      this.scDual,
      this.scFeatures,
      this.scSingle,
      this.scVideo,
      this.displayTest,
      this.performanceTest,
      this.images});

  factory SpecificationModel.fromJson(Map<String, dynamic> json) {
    return SpecificationModel(
      id: json['id'],
      brandId: json['brand_id'],
      title: json['title'],
      description: json['description'],
      technology: json['technology'],
      announced: json['announced'],
      status: json['status'],
      dimensions: json['dimensions'],
      weight: json['weight'],
      build: json['build'],
      sim: json['sim'],
      typeDisplay: json['type_display'],
      size: json['size'],
      resolution: json['resolution'],
      protection: json['protection'],
      os: json['os'],
      chipset: json['chipset'],
      cpu: json['cpu'],
      gpu: json['gpu'],
      cardSlot: json['card_slot'],
      internal: json['internal'],
      triple: json['triple'],
      features: json['features'],
      video: json['video'],
      loudSpeakerSound: json['loudspeaker_sound'],
      jack: json['jack'],
      wlan: json['wlan'],
      bluetooth: json['bluetooth'],
      gps: json['gps'],
      nfc: json['nfc'],
      radio: json['radio'],
      usb: json['usb'],
      sensors: json['sensors'],
      typeBattery: json['type_battery'],
      charging: json['charging'],
      colors: json['colors'],
      models: json['models'],
      sar: json['sar'],
      sarEU: json['sar_eu'],
      price: json['price'],
      camera: json['camera'],
      loudSpeakerTest: json['loudspeaker_test'],
      batteryLife: json['battery_life'],
      quad: json['quad'],
      single: json['single'],
      dual: json['dual'],
      scDual: json['sc_dual'],
      scFeatures: json['sc_features'],
      scSingle: json['sc_single'],
      scVideo: json['sc_video'],
      displayTest: json['display_test'],
      performanceTest: json['performance_test'],
      images: json["images"] != null ? List<String>.from(json["images"]) : null,
    );
  }
}
